server:
  port: 8088

spring:
  application:
    name: auth-service
  datasource:
    url: jdbc:mysql://localhost:3306/dmh_users_db?allowPublicKeyRetrieval=true&useSSL=false&serverTimezone=UTC
    username: dmh_user
    password: dmh_password
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false

jwt:
  # Para prod, definir JWT_SECRET en variables de entorno.
  secret: ${JWT_SECRET:XFcDq8zqrDCdaWIBa1a4xyAcplKL3ZIm8N3jpjRQHRhPD2vA59vT+TBKm0JtuujBuI24W4RNmyMG7Scu/i4nWQ==}
  # 24 horas en milisegundos.
  expiration: ${JWT_EXPIRATION:86400000}

eureka:
  instance:
    prefer-ip-address: true
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
