FROM maven:3.9.9-eclipse-temurin-17 AS build
WORKDIR /workspace

COPY . .

RUN mvn -pl auth-service -am -DskipTests package

FROM eclipse-temurin:17-jre
WORKDIR /app

COPY --from=build /workspace/auth-service/target/auth-service-1.0.0.jar app.jar

EXPOSE 8088
ENTRYPOINT ["java", "-jar", "app.jar"]

